#!/usr/bin/perl

$infile          = "";
$outfile         = "";
$tablewidth      = "4";
$tableheight     = "0";
$backgroundcolor = "black"; 
$imagedimensions = "256x256";

for (@ARGV) {
    /^-w$/ and do { push @nextargv, \$tablewidth;      next };
    /^-h$/ and do { push @nextargv, \$tableheight;     next };
    /^-c$/ and do { push @nextargv, \$backgroundcolor; next };
    /^-s$/ and do { push @nextargv, \$imagedimensions; next };
    /^-.+/ and do &usage;
    @nextargv and do { $r = shift @nextargv; $r and $$r = $_; next };
    !$infile  and do { $infile  = $_; next };
    !$outfile and do { $outfile = $_; next };
    &usage;
}

$infile = "-" if !$infile; $outfile = "-" if !$outfile;
open STDIN,  $infile      or die "Can't open $infile\n"  if $infile  ne "-";

($imagewidth, $imageheight) = split /x/, $imagedimensions;

$tableheight = 999999 if !$tableheight;

for (0..999999) {
    $s = sprintf "%s.%03d.html", $outfile, $_;
    open STDOUT, ">>$s" or die "Can't open $s\n" if $outfile ne "-";
    print "<html>\n<body bgcolor=\"$backgroundcolor\">\n<table align=\"center\">\n";
    for (1..$tableheight) {
	print "  <tr>\n";
        for (1..$tablewidth) {
	    ($name, $uri, $subject, $author, $date, $id, $bytes) = split /\t/, <STDIN>;
	    print "    <td>\n"
	        . "      <a href=\"$uri\" target=\"_blank\">\n"
	        . "        <img src=\"$uri\" width=$imagewidth height=$imageheight border=0>\n"
	        . "      </a>\n"
	        . "    </td>\n";
	    last if eof STDIN;
	}
	last if eof STDIN;
    }
    print "  </tr>\n";
    print "</table>\n</body>\n</html>\n";
    close STDOUT;
    last if eof STDIN;
}


sub usage {
    die "Usage: ./thumbnails [options] [infile] [outfile-prefix]\n\n"
      . "  -w  Table width. (default 4)\n"
      . "  -h  Table height. (default infinite)\n"
      . "  -c  Background color. (default black)\n"
      . "  -s  Image dimensions, of form WxH. (default \"256x256\")\n"
      . "\n";
}

