//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NodeConfig.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_GETSEEDDLG                  102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_TITLE                       104
#define IDS_NOTCONNECTED                105
#define IDS_ERR_GETSEED                 106
#define IDD_PP_NORMAL                   107
#define IDS_ERR_NOWININET               107
#define IDD_PP_ADVANCED                 108
#define IDD_PP_GEEK                     109
#define IDR_MAINFRAME                   128
#define IDD_DLG_PERM_WARN               129
#define IDD_PP_FPROXY                   130
#define IDD_PP_DIAGNOSTICS              131
#define IDD_EDITUNKNOWN                 134
#define IDC_storeSize                   1000
#define IDC_announcementAttempts        1002
#define IDC_fproxy_inserthtl            1003
#define IDC_GETSEED                     1004
#define IDC_fproxy_requesthtl           1006
#define IDC_SEEDURL                     1007
#define IDC_ipAddress                   1009
#define IDC_listenPort                  1010
#define IDC_clientPort                  1011
#define IDC_fcpHosts                    1012
#define IDC_bandwidthLimit              1013
#define IDC_bandwidthLimit_spin         1014
#define IDC_outputBandwidthLimit        1015
#define IDC_outputBandwidthLimit_spin   1016
#define IDC_inputBandwidthLimit         1017
#define IDC_inputBandwidthLimit_spin    1018
#define IDC_initialRequestHTL           1019
#define IDC_initialRequestHTL_spin      1020
#define IDC_maxHopsToLive               1021
#define IDC_maxHopsToLive_spin          1022
#define IDC_maximumThreads              1023
#define IDC_maximumThreads_spin         1024
#define IDC_adminPassword               1025
#define IDC_announcementDelay           1026
#define IDC_announcementDelayBase       1027
#define IDC_maxNodeConnections_spin     1028
#define IDC_announcementPeers           1029
#define IDC_doDiagnostics               1030
#define IDC_diagnosticsPath             1031
#define IDC_logFile                     1032
#define IDC_logLevel                    1033
#define IDC_authTimeout                 1035
#define IDC_checkPointInterval          1037
#define IDC_blockSize                   1038
#define IDC_connectionTimeout           1039
#define IDC_hopTimeExpected             1040
#define IDC_hopTimeDeviation            1041
#define IDC_storeFile                   1042
#define IDC_storeDataFile               1043
#define IDC_localAnnounceTargets        1044
#define IDC_messageStoreSize            1045
#define IDC_routeConnectTimeout         1046
#define IDC_rtMaxNodes                  1047
#define IDC_rtMaxRefs                   1048
#define IDC_streamBufferSize            1049
#define IDC_initialRequests             1050
#define IDC_storeCacheSize_spin         1052
#define IDC_notTransient                1053
#define IDC_ipAddress_TITLE             1054
#define IDC_listenPort_TITLE            1055
#define IDC_DONT_WARN_PERM              1056
#define IDC_fproxy_port                 1061
#define IDC_FPROXYPORT_TITLE            1062
#define IDC_fproxy_class                1063
#define IDC_FPROXYFILTER                1064
#define IDC_FPROXYSERVICE               1065
#define IDC_FPROXYALLOWEDMIME           1066
#define IDC_FPROXYDROPPEDCONN           1068
#define IDC_fproxy_splitthreads         1069
#define IDC_SEEDFILE                    1070
#define IDC_BSHOWNEWBUILDWARNING        1070
#define IDC_NODEINFOSERVLET             1071
#define IDC_useDefaultNodeRefs          1072
#define IDC_NODEINFOPORT                1073
#define IDC_fproxy_splitretries         1074
#define IDC_NODEINFOCLASS               1075
#define IDC_importNewNodeRef            1076
#define IDC_logFormat                   1077
#define IDC_fproxy_splitincHTL          1078
#define IDC_GETLOCALSEED                1079
#define IDC_maxNodeConnections          1080
#define IDC_BUT_exportRef               1081
#define IDC_storeCipherName             1082
#define IDC_transient                   1083
#define IDC_storeCipherWidth            1084
#define IDC_DLOADPROGRESS               1085
#define IDC_maximumPadding              1086
#define IDC_doAnnounce                  1087
#define IDC_slider_CPUPriority          1088
#define IDC_Static_CPUPriority          1089
#define IDC_storePath_browse            1090
#define IDC_FAILURETABENTRIES           1091
#define IDC_FAILURETABENTRIESSPIN       1092
#define IDC_BINBOUNDCONTACTS            1093
#define IDC_FAILURETABTIME              1095
#define IDC_adminPeer                   1095
#define IDC_FAILURETABTIMESPIN          1096
#define IDC_RANDOMIZEPORT               1096
#define IDC_BOUTBOUNDCONTACTS           1097
#define IDC_BINBOUNDREQUESTS            1098
#define IDC_CHECK_CHANGENODEADDRESS     1098
#define IDC_BOUTBOUNDREQUESTS           1099
#define IDC_CHECK_AUTOIP                1099
#define IDC_STATIC_NODEAVAILABILITY_FRAME 1099
#define IDC_LISTOFUNKNOWN               1100
#define IDC_STATIC_NODEADDRESS_COLON    1100
#define IDC_ADDTHIS                     1102
#define IDC_ADDIT                       1105
#define IDC_DELETE                      1106
#define IDC_CANCEL                      1107
#define IDC_UNKNOWN                     1108
#define IDC_NUMUNKNOWN                  1109
#define IDC_MOVEUP                      1111
#define IDC_MOVEDOWN                    1112
#define IDC_storeType                   1113
#define IDC_tempFile                    1114
#define IDC_tempFile_browser            1115

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
