#!/usr/bin/perl -w

use strict;
use Socket;
use IO::SendFile qw( sendfile );
$|++;
unless (@ARGV == 2 && -d $ARGV[0]) {
    print "Usage: $0 <directory to insert> <directory to create>\n";
    exit 1;
}
$ARGV[0] =~ s/\/$//g;
$ARGV[1] =~ s/\/$//g;
recurse($ARGV[0], $ARGV[1]);

sub recurse {
    my ($from, $to) = @_;
    mkdir($to, 0755);
    opendir DIR, $from;
    my @dir = readdir DIR;
    for (sort @dir) {
	/^\./ and next;
	my $f = "$from/$_";
	my $t = "$to/$_";
	-d $f and recurse($f, $t);
	-f $f and insert($f, $t);
    }
}

sub insert {
    my ($file, $out) = @_;
    my $len = -s $file;
    my $sock = conn();
    print "Inserting $file.\n";
    syswrite($sock, "i");
    syswrite($sock, pack('V', $len));
    my $off = 0;
    open(FH, $file) or die "open() failed!";
    sendfile(fileno($sock), fileno(FH), $off, $len);
    sysread($sock, $len, 4);
    $len = unpack('V', $len);
    my $key;
    sysread($sock, $key, $len);
    close(FH);
    open(FH, ">$out") or die "open() failed!";
    syswrite(FH, $key, $len);
    close(FH);
    close $sock;
}

sub conn {
    local *SOCK;
    socket(SOCK, PF_INET, SOCK_STREAM, getprotobyname('tcp')) or die "socket: $!";
    connect(SOCK, sockaddr_in(9993, inet_aton('127.0.0.1'))) or die "connect: $!";
    select +((select SOCK), ($|++))[0];
    return *SOCK;
}
