/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onionnetworks_fec_Native8Code */

#ifndef _Included_com_onionnetworks_fec_Native8Code
#define _Included_com_onionnetworks_fec_Native8Code
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_onionnetworks_fec_Native8Code
 * Method:    nativeEncode
 * Signature: (J[[B[I[I[[B[III)V
 */
JNIEXPORT void JNICALL Java_com_onionnetworks_fec_Native8Code_nativeEncode
  (JNIEnv *, jobject, jlong, jobjectArray, jintArray, jintArray, jobjectArray, jintArray, jint, jint);

/*
 * Class:     com_onionnetworks_fec_Native8Code
 * Method:    nativeDecode
 * Signature: (J[[B[I[III)V
 */
JNIEXPORT void JNICALL Java_com_onionnetworks_fec_Native8Code_nativeDecode
  (JNIEnv *, jobject, jlong, jobjectArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_onionnetworks_fec_Native8Code
 * Method:    nativeNewFEC
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_onionnetworks_fec_Native8Code_nativeNewFEC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_onionnetworks_fec_Native8Code
 * Method:    nativeFreeFEC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_onionnetworks_fec_Native8Code_nativeFreeFEC
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
