/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onionnetworks_fec_Native16Code */

#ifndef _Included_com_onionnetworks_fec_Native16Code
#define _Included_com_onionnetworks_fec_Native16Code
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: initialized */
/*
 * Class:     com_onionnetworks_fec_Native16Code
 * Method:    nativeEncode
 * Signature: (I[[B[I[I[[B[III)V
 */
JNIEXPORT void JNICALL Java_com_onionnetworks_fec_Native16Code_nativeEncode
  (JNIEnv *, jobject, jint, jobjectArray, jintArray, jintArray, jobjectArray, jintArray, jint, jint);

/*
 * Class:     com_onionnetworks_fec_Native16Code
 * Method:    nativeDecode
 * Signature: (I[[B[I[III)V
 */
JNIEXPORT void JNICALL Java_com_onionnetworks_fec_Native16Code_nativeDecode
  (JNIEnv *, jobject, jint, jobjectArray, jintArray, jintArray, jint, jint);

/*
 * Class:     com_onionnetworks_fec_Native16Code
 * Method:    nativeNewFEC
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_onionnetworks_fec_Native16Code_nativeNewFEC
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_onionnetworks_fec_Native16Code
 * Method:    nativeFreeFEC
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_onionnetworks_fec_Native16Code_nativeFreeFEC
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
